### ISSUE TITLE
Dock Icon Not Updating

### ISSUE THREAD

**Issue by londoncollin** [SAP/macOS-enterprise-privileges#38] opened 2022-07-17 21:56 UTC
The icon is not changing to black with a yellow outline and an unlocked padlock icon when privilege requested administrator. It remains green and locked. The message box states "You are currently an Administrator". Version is 1.5.3 on macOS Monterey.

<img width="484" alt="Screen Shot 2022-07-17 at 16 55 05" src="https://user-images.githubusercontent.com/36442621/179426256-3e8a6fef-d8eb-4998-8cff-b1f982a1d83c.png">

**Comment by Akshay-Thakare** [comment] 2022-07-18 14:36
+1 facing same issue

**Comment by moobyfr** [comment] 2022-07-21 13:20
I had the same problem, it's a packaging error

**Comment by alexbrothman** [comment] 2022-10-21 17:44
I have Privileges running on multiple machines, yet the only one that changes the icon color after Admin privs are requested is my own. Working as Admin, I download the Release version from GitHub and drag the app into the Apps folder every time I setup a new machine, so I don't believe the issue is related to the deployment process. All of our machines are running Monterey and v1.5.3 of Privileges.

**Comment by tianjun-orby** [comment] 2023-03-08 17:46
Same problem, no icon change. Installed it using the same way Alex mentioned above.

**Comment by fortiko** [comment] 2023-09-22 21:02
Just to confirm, this is still an issue. Happened the first time to me after an upgrade via Homebrew, previous upgrades worked just fine.  Upgraded to 1.5.4 and now I observe the same that the icon doesn't reflect elevation. Thanks for looking into it!

**Comment by fortiko** [comment] 2023-09-22 21:13
Reverting via installing the original 1.5.3 PKG fixes it, even without rebooting. Happy to help with logs to get to the bottom of this.

**Comment by clevelandbread** [comment] 2023-10-10 19:22
Will this get fixed in the 1.5.4 version by chance?

**Comment by nberanger** [comment] 2023-11-09 17:13
Using AutoPKG to get the PKG file solved this issue for me with 1.5.4.

**Closed** 2024-03-06 15:21 UTC

**Comment by dqrfe** [comment] 2024-03-21 16:00
We are also experiencing issues with version 1.5.4. However, it seems that these problems are only occurring on specific clients. Additionally, there are instances where the right-click menu is missing upon clicking the dock app icon. Does anyone have any insights or ideas regarding this matter?
